# Generated by Django 3.0.7 on 2020-07-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='datanascimento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='placa',
            field=models.CharField(blank=True, default='-', max_length=7),
        ),
    ]
