# Generated by Django 3.0.7 on 2020-06-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agente',
            old_name='gritodeduerra',
            new_name='gritodeguerra',
        ),
    ]
