# Generated by Django 3.0.7 on 2020-07-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200720_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='datanascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
