# Generated by Django 3.0.7 on 2020-06-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200627_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alocacao',
            name='local',
        ),
        migrations.AddField(
            model_name='alocacao',
            name='bairro',
            field=models.CharField(default='Não informado', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alocacao',
            name='complemento',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='numero',
            field=models.CharField(default='Não informado', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alocacao',
            name='rua',
            field=models.CharField(default='Não informado', max_length=200),
            preserve_default=False,
        ),
    ]
