# Generated by Django 3.0.7 on 2020-07-01 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200630_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='viatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Viatura'),
        ),
    ]
