# Generated by Django 3.0.7 on 2020-07-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200630_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alocacaorecolhimento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='alocacaorecolhimento',
            name='horario',
        ),
        migrations.AddField(
            model_name='alocacao',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado'), ('Desativado', 'Desativado')], default='Fechado', max_length=11),
        ),
    ]
