# Generated by Django 3.0.7 on 2020-07-01 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200701_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacaorecolhimento',
            name='alocacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Alocacao'),
        ),
        migrations.AlterField(
            model_name='alocacaorecolhimento',
            name='recolhimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Recolhimento'),
        ),
    ]
