# Generated by Django 3.0.7 on 2020-07-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20200701_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='recolhimento',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recolhimento',
            name='turno',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Madrugada', 'Madrugada')], default='Não informado', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recolhimento',
            name='viatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.Viatura'),
        ),
    ]
