# Generated by Django 3.0.7 on 2020-07-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200703_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recolhimento',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
