# Generated by Django 3.0.7 on 2020-07-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20200703_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recolhimento',
            name='quantidade',
        ),
    ]
