# Generated by Django 3.0.7 on 2020-07-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_recolhimento_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='recolhimento',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
